name: Promote tag to release branch

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tagged commit
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Push to release branch
        run: git push origin HEAD:refs/heads/release --force
